<%@ page import= "java.util.List" %>
<%@ page import= "board.BoardMgr" %>
<%@ page import= "board.boardBean" %>
<%@ page import= "board.commentBean" %>
<%@ page import= "board.commentMgr" %>
<%@ page import= "board.NotificationMgr" %>
<%@ page import= "user.Member_Mgr" %>
<%@ page import = "imoticon.imoticonMgr" %>
<%@ page import = "imoticon.imoticonBean" %>